import type { CanonicalEvidence, CanonicalFact, IsoDate, SectionId } from "./contracts";
import { currentCorpus, validateCorpus } from "./corpusValidation.js";

function source(
  sourceId: string,
  sectionId: SectionId,
  title: string,
  searchTerms: readonly string[],
  facts: readonly CanonicalFact[],
): CanonicalEvidence {
  return { sourceId, sectionId, title, searchTerms, facts };
}

const assistantCorpus: readonly CanonicalEvidence[] = [
  source(
    "assistant-identity",
    "about",
    "Ask Rodrigo · Assistant identity and boundaries",
    ["assistant", "name", "alfred", "identity", "nombre", "asistente", "como te llamas"],
    [
      {
        factId: "assistant-identity-name",
        text: "Rodrigo's public assistant is named Alfred.",
        entities: ["Alfred", "Ask Rodrigo"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "assistant-identity-not-rodrigo",
        text: "Alfred is Rodrigo Uroz's professional assistant, not Rodrigo himself.",
        entities: ["Alfred", "Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "assistant-identity-public-only",
        text: "Alfred answers from Rodrigo's approved public corpus and has no access to private repositories or private information.",
        entities: ["Alfred", "Ask Rodrigo"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "assistant-identity-fallback",
        text: "If the public corpus does not support an answer, Alfred directs the visitor to Rodrigo instead of guessing.",
        entities: ["Alfred", "Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "career-overview",
    "experience",
    "Professional experience overview",
    [
      "career",
      "professional experience",
      "work history",
      "companies",
      "roles",
      "best suited",
      "role fit",
      "problem fit",
      "mejor encaje",
      "tipos de problemas",
      "large scale",
      "millions of users",
      "zero to one",
      "hands-on engineer",
      "escala",
      "millones de usuarios",
      "desde cero",
      "availability",
      "open to work",
      "disponible",
      "abierto a propuestas",
      "trayectoria",
      "experiencia profesional",
      "empresas",
    ],
    [
      {
        factId: "career-years",
        text: "Rodrigo has built software professionally since 2000, giving him more than 25 years of experience by 2026.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "career-positioning",
        text: "Rodrigo is a software and product engineer who turns ambiguous problems into working products and the systems needed to run them.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "career-end-to-end",
        text: "He moves between product definition, domain modeling, architecture, hands-on implementation, validation, and technical leadership.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "career-scale-and-zero-to-one",
        text: "Rodrigo's experience spans large-scale products, legacy modernization, engineering leadership, and new products built from zero as a hands-on engineer.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "career-millions-scale",
        text: "Rodrigo has worked on products used by millions of people, including systems at Medallia, ClassDojo, and Bumeran.",
        entities: ["Rodrigo Uroz", "Medallia", "ClassDojo", "Bumeran"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "career-companies",
        text: "His public career history includes ClassDojo, SCVSoft, Medallia, FutureAdvisor through SCVSoft, VSKO, DLA TV, OpenEnglish through TeraCode, Bumeran, Globant, and Claxson.",
        entities: [
          "ClassDojo",
          "SCVSoft",
          "Medallia",
          "FutureAdvisor",
          "VSKO",
          "DLA TV",
          "OpenEnglish",
          "TeraCode",
          "Bumeran",
          "Globant",
          "Claxson",
        ],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "career-roles",
        text: "His roles have ranged from individual contributor and technical lead to engineering manager, Head of Development, and Project Manager.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "career-openness",
        text: "As of August 25, 2026, Rodrigo is open to roles and collaborations that combine product judgment with hands-on engineering, especially around ambiguous requirements, complex domains, or difficult integrations; he is not focused on one industry.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
    ],
  ),
  source(
    "classdojo-current-role",
    "experience",
    "ClassDojo · Experience",
    [
      "classdojo",
      "fullstack",
      "aws",
      "kubernetes",
      "current employer",
      "work now",
      "works now",
      "empleador actual",
      "trabaja ahora",
    ],
    [
      {
        factId: "classdojo-role-period",
        text: "Rodrigo joined ClassDojo on January 1, 2022 as a Fullstack Software Engineer.",
        entities: ["Rodrigo Uroz", "ClassDojo"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "classdojo-current-employment",
        text: "As of August 25, 2026, ClassDojo is Rodrigo's current employer.",
        entities: ["Rodrigo Uroz", "ClassDojo"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
      {
        factId: "classdojo-cloud",
        text: "His ClassDojo work includes production systems on AWS and Kubernetes.",
        entities: ["Rodrigo Uroz", "ClassDojo", "AWS", "Kubernetes"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "classdojo-platform-modernization",
    "experience",
    "ClassDojo · Platform modernization",
    [
      "classdojo",
      "platform modernization",
      "typescript migration",
      "web monorepo",
      "ci",
      "deployment",
      "realtime reliability",
      "modernizacion de plataforma",
      "migracion a typescript",
      "monorepo web",
      "integracion continua",
      "confiabilidad",
    ],
    [
      {
        factId: "classdojo-typescript",
        text: "Rodrigo helped migrate ClassDojo's web monorepo to TypeScript incrementally so product work could continue while type coverage and shared contracts improved.",
        entities: ["Rodrigo Uroz", "ClassDojo", "TypeScript"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-platform-developer-productivity",
        text: "His platform work included API type utilities, migration tracking, type checking, and CI and deployment workflow improvements.",
        entities: ["Rodrigo Uroz", "ClassDojo"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-platform-reliability",
        text: "He also worked on reliability and observability for real-time product behavior rather than treating modernization as a type-only effort.",
        entities: ["Rodrigo Uroz", "ClassDojo"],
        reviewedAt: "2026-08-26",
      },
    ],
  ),
  source(
    "classdojo-tutor-product",
    "experience",
    "ClassDojo · Tutor product",
    [
      "classdojo",
      "tutor",
      "tutoring",
      "marketplace",
      "product integration",
      "availability",
      "scheduling",
      "zoom",
      "attendance",
      "subscriptions",
      "experiments",
      "tutoria",
      "integracion de producto",
      "disponibilidad",
      "agenda",
      "asistencia",
      "suscripciones",
      "experimentos",
    ],
    [
      {
        factId: "classdojo-external-product",
        text: "Rodrigo helped integrate an externally developed tutoring product into ClassDojo's architecture and operating environment.",
        entities: ["Rodrigo Uroz", "ClassDojo", "Tutor"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-tutor-fullstack",
        text: "He worked across the Tutor backend, customer-facing web experience, and administrative tools instead of owning only one application layer.",
        entities: ["Rodrigo Uroz", "ClassDojo", "Tutor"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-tutor-scheduling",
        text: "His Tutor work included tutor availability, scheduling, sessions, time-zone behavior, and attendance flows.",
        entities: ["Rodrigo Uroz", "ClassDojo", "Tutor"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-zoom",
        text: "The Tutor integration connected scheduled classes to Zoom.",
        entities: ["ClassDojo", "Tutor", "Zoom"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-tutor-commercial-flows",
        text: "He contributed to subscription, payment, pricing, trial, and product-experiment flows around Tutor.",
        entities: ["Rodrigo Uroz", "ClassDojo", "Tutor"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-tutor-operability",
        text: "He also worked on notifications, analytics events, automated tests, staging support, and operational fixes needed to run Tutor as part of ClassDojo.",
        entities: ["Rodrigo Uroz", "ClassDojo", "Tutor"],
        reviewedAt: "2026-08-26",
      },
    ],
  ),
  source(
    "classdojo-district-solutions",
    "experience",
    "ClassDojo · District communications and insights",
    [
      "classdojo",
      "district solutions",
      "school insights",
      "communication insights",
      "district announcements",
      "bulletins",
      "audience",
      "distribution lists",
      "sis",
      "rostering",
      "exports",
      "email sms voice",
      "observability",
      "comunicaciones distritales",
      "insights escolares",
      "audiencias",
      "listas de distribucion",
      "padrones",
      "exportaciones",
      "confiabilidad",
    ],
    [
      {
        factId: "classdojo-district-focus",
        text: "Rodrigo's District Solutions work covers communication, announcement, and insight products at both district and school scope.",
        entities: ["Rodrigo Uroz", "ClassDojo", "District Solutions"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-audience-modeling",
        text: "He has worked on recipient and audience modeling across ClassDojo accounts, classes, schools, districts, distribution lists, and roster or SIS data.",
        entities: ["Rodrigo Uroz", "ClassDojo", "SIS"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-multichannel-communications",
        text: "His communications work includes email, SMS, voice, and in-product delivery concerns, including recipient resolution and delivery-state behavior.",
        entities: ["Rodrigo Uroz", "ClassDojo", "District Solutions"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-communications-operability",
        text: "He has worked on recipient exports, failure states, queue behavior, monitoring, and operational diagnostics for communication workflows.",
        entities: ["Rodrigo Uroz", "ClassDojo", "District Solutions"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-insights-composition",
        text: "For School Insights, Rodrigo worked on composing product-level communication facts from messaging, stories, calendar, school, and rostering domains while keeping ownership boundaries explicit.",
        entities: ["Rodrigo Uroz", "ClassDojo", "School Insights"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-insights-data-semantics",
        text: "He treats true zeroes, unavailable metrics, account status, and roster-source differences as explicit product, API, sorting, and presentation semantics.",
        entities: ["Rodrigo Uroz", "ClassDojo", "School Insights"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-district-end-to-end",
        text: "This work has crossed backend services, frontend experiences, exports, automated tests, performance analysis, staged rollout, and production validation.",
        entities: ["Rodrigo Uroz", "ClassDojo", "District Solutions"],
        reviewedAt: "2026-08-26",
      },
    ],
  ),
  source(
    "classdojo-ai-engineering",
    "experience",
    "ClassDojo · AI product and developer workflows",
    [
      "classdojo",
      "artificial intelligence",
      "ai product",
      "llm",
      "langfuse",
      "grounding",
      "structured output",
      "coding agents",
      "agent skills",
      "conductor",
      "developer experience",
      "inteligencia artificial",
      "producto con ia",
      "agentes de codigo",
      "habilidades de agentes",
      "experiencia de desarrollo",
    ],
    [
      {
        factId: "classdojo-llms",
        text: "Rodrigo contributed to ClassDojo's early LLM product features and to later AI-assisted product and developer workflows.",
        entities: ["Rodrigo Uroz", "ClassDojo", "LLMs"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-langfuse",
        text: "His LLM work at ClassDojo has included prompt management, tracing, and evaluation with Langfuse.",
        entities: ["Rodrigo Uroz", "ClassDojo", "Langfuse"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-bounded-ai",
        text: "His applied-AI work keeps model behavior behind explicit context, structured contracts, validation, observable traces, and tested failure paths.",
        entities: ["Rodrigo Uroz", "ClassDojo", "LLMs"],
        reviewedAt: "2026-08-26",
      },
      {
        factId: "classdojo-orchestrators",
        text: "Rodrigo evaluates LLMs and orchestration tools as their capabilities change.",
        entities: ["Rodrigo Uroz", "LLMs"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "classdojo-orchestrators-current",
        text: "As of August 25, 2026, Rodrigo uses Conductor in this work.",
        entities: ["Rodrigo Uroz", "Conductor"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
      {
        factId: "classdojo-skills-dx",
        text: "Rodrigo works with ClassDojo's in-house agent skills and coding-agent workflows, evaluating tools by whether they improve developer experience and verified delivery.",
        entities: ["Rodrigo Uroz", "ClassDojo"],
        reviewedAt: "2026-08-26",
        expiresAt: "2026-11-26",
      },
    ],
  ),
  source(
    "scvsoft-iot-tech-lead",
    "experience",
    "SCVSoft · Experience",
    [
      "scvsoft",
      "iot",
      "tech lead",
      "third-party api",
      "reverse engineering",
      "hotels",
      "buildings",
      "dispositivos",
      "ingenieria inversa",
    ],
    [
      {
        factId: "scvsoft-period-role",
        text: "Rodrigo worked at SCVSoft from July through December 2021 as a Tech Lead.",
        entities: ["Rodrigo Uroz", "SCVSoft"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "scvsoft-client",
        text: "Through SCVSoft, he worked for an unnamed B2B IoT client serving hotels and commercial buildings.",
        entities: ["Rodrigo Uroz", "SCVSoft"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "scvsoft-aggregator",
        text: "The service hid provider and device differences behind one interface.",
        entities: ["SCVSoft"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "scvsoft-reverse-engineering",
        text: "Rodrigo reverse-engineered devices whose APIs were incomplete or difficult to interpret.",
        entities: ["Rodrigo Uroz", "SCVSoft"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "medallia-engineering-management",
    "experience",
    "Medallia · Experience",
    [
      "medallia",
      "engineering manager",
      "frontend team",
      "angular",
      "react",
      "redux",
      "graphql",
      "leadership",
      "equipo frontend",
    ],
    [
      {
        factId: "medallia-period-role",
        text: "Rodrigo worked at Medallia from December 2018 through July 2021 as a Senior Engineering Manager.",
        entities: ["Rodrigo Uroz", "Medallia"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "medallia-team",
        text: "He managed a frontend team of about ten people across three cities.",
        entities: ["Rodrigo Uroz", "Medallia"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "medallia-modernization",
        text: "His team rebuilt seven legacy Angular applications with React and Redux.",
        entities: ["Medallia", "Angular", "React", "Redux"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "medallia-graphql",
        text: "The modernization moved client integration from REST toward GraphQL.",
        entities: ["Medallia", "REST", "GraphQL"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "medallia-scale",
        text: "Thousands of Medallia customers used the products maintained by his team.",
        entities: ["Medallia"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "futureadvisor-lead-engineer",
    "experience",
    "FutureAdvisor / SCVSoft · Experience",
    [
      "futureadvisor",
      "scvsoft",
      "lead engineer",
      "performance",
      "processing workflow",
      "faster",
      "cheaper",
      "cost",
      "rails",
      "postgresql",
      "react",
      "redux",
      "aws",
      "sqs",
      "sns",
      "batch",
      "lambda",
      "portfolio",
    ],
    [
      {
        factId: "futureadvisor-period-role",
        text: "Rodrigo worked on FutureAdvisor through SCVSoft from September 2016 through December 2018 as a Lead Software Engineer.",
        entities: ["Rodrigo Uroz", "FutureAdvisor", "SCVSoft"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "futureadvisor-team",
        text: "He led a six-engineer team.",
        entities: ["Rodrigo Uroz", "FutureAdvisor"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "futureadvisor-stack",
        text: "FutureAdvisor used Rails and PostgreSQL on the backend and React with Redux on the frontend.",
        entities: ["FutureAdvisor", "Rails", "PostgreSQL", "React", "Redux"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "futureadvisor-services",
        text: "His team moved selected workloads out of a monolith into AWS services such as SQS, SNS, Batch, and Lambda.",
        entities: ["FutureAdvisor", "AWS", "SQS", "SNS", "Batch", "Lambda"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "futureadvisor-outcome",
        text: "The team cut a daily processing workflow from about three hours to about fifty minutes and reduced its cost by roughly half.",
        entities: ["FutureAdvisor"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "vsko-education-software",
    "experience",
    "Lemonade / VSKO · Experience",
    [
      "lemonade",
      "vsko",
      "belgian",
      "belgium",
      "catholic schools",
      "education software",
      "java",
      "jersey",
      "google api",
      "node",
      "angularjs",
    ],
    [
      {
        factId: "vsko-period-role",
        text: "Rodrigo worked on VSKO through Lemonade from 2013 to 2016 as a Software Engineer.",
        entities: ["Rodrigo Uroz", "VSKO", "Lemonade"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "vsko-product",
        text: "He built classroom and administration software for Catholic schools in Belgium.",
        entities: ["Rodrigo Uroz", "VSKO"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "vsko-stack",
        text: "The product combined Java and Jersey services, Google APIs, SQL databases, Node.js, and AngularJS.",
        entities: ["VSKO", "Java", "Jersey", "PostgreSQL", "MySQL", "Node.js", "AngularJS"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "vsko-english",
        text: "Rodrigo communicated with the Belgian client in English.",
        entities: ["Rodrigo Uroz", "VSKO"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "dla-team-and-qa",
    "experience",
    "DLA TV · Experience",
    [
      "dla",
      "head of development",
      "qa",
      "team building",
      "hiring",
      "training",
      "delivery process",
      "equipo",
      "contratacion",
    ],
    [
      {
        factId: "dla-period-role",
        text: "Rodrigo worked at DLA TV from 2012 to 2013 as Head of Development.",
        entities: ["Rodrigo Uroz", "DLA TV"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "dla-qa",
        text: "He established DLA TV's first QA team.",
        entities: ["Rodrigo Uroz", "DLA TV"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "dla-growth",
        text: "He expanded the development team and took responsibility for hiring, training, and delivery practices.",
        entities: ["Rodrigo Uroz", "DLA TV"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "openenglish-engagement",
    "experience",
    "TeraCode / OpenEnglish · Experience",
    [
      "teracode",
      "openenglish",
      "project manager",
      "individual contributor",
      "30 people",
      "ic",
      "gerente de proyecto",
    ],
    [
      {
        factId: "openenglish-period",
        text: "Rodrigo worked on OpenEnglish through TeraCode from 2009 to 2012; OpenEnglish was a client, not his employer.",
        entities: ["Rodrigo Uroz", "OpenEnglish", "TeraCode"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "openenglish-progression",
        text: "He began as an individual contributor, later became Project Manager, and grew TeraCode's OpenEnglish engagement to roughly thirty people.",
        entities: ["Rodrigo Uroz", "OpenEnglish", "TeraCode"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "bumeran-search",
    "experience",
    "Bumeran · Experience",
    ["bumeran", "php", "java", "solr", "search engine", "resumes", "cvs", "buscador"],
    [
      {
        factId: "bumeran-period-role",
        text: "Rodrigo worked at Bumeran from 2007 to 2009 as a Software Engineer.",
        entities: ["Rodrigo Uroz", "Bumeran"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "bumeran-stack-search",
        text: "He worked on Bumeran's PHP backend and built a Java and Solr search engine for candidate résumés.",
        entities: ["Rodrigo Uroz", "Bumeran", "PHP", "Java", "Solr"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "globant-functional-analysis",
    "experience",
    "Globant · Experience",
    ["globant", "functional analyst", "marketplace", "refactor", "analisis funcional"],
    [
      {
        factId: "globant-period-role",
        text: "Rodrigo worked at Globant from 2006 to 2007 as a Functional Analyst.",
        entities: ["Rodrigo Uroz", "Globant"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "globant-marketplace",
        text: "He led functional analysis for a marketplace refactor.",
        entities: ["Rodrigo Uroz", "Globant"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "mixplay-streaming",
    "experience",
    "Claxson / Mixplay · Experience",
    ["claxson", "mixplay", "streaming", "php", "oracle", "csharp", "drm", "encryption"],
    [
      {
        factId: "mixplay-period-role",
        text: "Rodrigo worked at Claxson on Mixplay from 2003 to 2006 as a Senior Developer.",
        entities: ["Rodrigo Uroz", "Claxson", "Mixplay"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "mixplay-platform",
        text: "Rodrigo built the Mixplay streaming platform with PHP, Oracle, and C#, including DRM and content encryption.",
        entities: ["Rodrigo Uroz", "Mixplay", "PHP", "Oracle", "C#", "DRM"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "product-engineering-capability",
    "capabilities",
    "Product engineering · Capabilities",
    [
      "product engineer",
      "software engineer",
      "zero to one",
      "developer experience",
      "25 years",
      "end to end",
      "ambiguity",
      "requirements elicitation",
      "rapid prototype",
      "prototype and iterate",
      "producto",
      "ambiguedad",
      "relevamiento de requerimientos",
      "prototipo rapido",
    ],
    [
      {
        factId: "product-zero-to-one",
        text: "Rodrigo has repeatedly taken unclear product and domain problems from an initial idea to working software.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "product-operation",
        text: "He can define a product, model its domain, design the architecture, write the software, validate it, and help operate it.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "product-project-examples",
        text: "Rodrigo independently designed and built Coro, Traza, Daturno, Ballast, and Jacara.",
        entities: ["Rodrigo Uroz", "Coro", "Traza", "Daturno", "Ballast", "Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "product-ambiguity-method",
        text: "When requirements are ambiguous, Rodrigo first tries to reduce the ambiguity with an appropriate requirements-elicitation technique; sometimes the best way forward is to build a rapid prototype and iterate.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "systems-boundary-capability",
    "capabilities",
    "Provider-independent systems · Capabilities",
    [
      "provider independent",
      "domain boundaries",
      "domain concept",
      "domain model boundary",
      "first-class concept",
      "requirements vocabulary",
      "external apis",
      "unstable providers",
      "heterogeneous data",
      "common interface",
      "independiente del proveedor",
      "limites de dominio",
      "concepto de dominio",
      "frontera del modelo de dominio",
      "concepto de primer nivel",
      "vocabulario de requerimientos",
      "apis externas",
      "proveedores inestables",
      "datos heterogeneos",
      "interfaz comun",
    ],
    [
      {
        factId: "systems-provider-independent-models",
        text: "Across IoT, finance, scheduling, conversational systems, and family games, Rodrigo designs domain models that keep providers and device capabilities behind explicit contracts.",
        entities: ["Rodrigo Uroz", "SCVSoft", "Traza", "Daturno", "Coro", "Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "systems-messy-inputs",
        text: "His projects repeatedly address cases where user language, provider data, and operational rules do not map cleanly to one another.",
        entities: ["Rodrigo Uroz", "Traza", "Daturno", "Coro", "Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "systems-domain-boundary-criterion",
        text: "Rodrigo gives a concept its own domain-model boundary when it is a clear, self-contained, first-class term that appears repeatedly in the requirements.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "ai-engineering-principles",
    "capabilities",
    "AI engineering · Working principles",
    [
      "when to use llm",
      "deterministic core",
      "bounded ai",
      "probabilistic behavior",
      "model independent",
      "fallbacks",
      "observable decisions",
      "privacy boundaries",
      "cuando usar llm",
      "nucleo determinista",
      "ia acotada",
      "comportamiento probabilistico",
      "modelos reemplazables",
      "decisiones observables",
      "limites de privacidad",
    ],
    [
      {
        factId: "ai-deterministic-core",
        text: "Rodrigo keeps product-critical behavior deterministic and uses language models for bounded tasks where ambiguity cannot be removed with rules alone.",
        entities: ["Rodrigo Uroz", "LLMs"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ai-replaceable-models",
        text: "He treats models and model infrastructure as replaceable implementation choices rather than as the product's center.",
        entities: ["Rodrigo Uroz", "LLMs"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ai-operational-guardrails",
        text: "In AI-assisted systems, Rodrigo designs explicit fallbacks, observable decisions, and privacy boundaries around probabilistic behavior.",
        entities: ["Rodrigo Uroz", "LLMs"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "openclaw-contributions",
    "capabilities",
    "OpenClaw · Open-source contributions",
    [
      "openclaw",
      "open source",
      "memory system",
      "hybrid search",
      "mmr",
      "temporal decay",
      "compaction safeguards",
      "post-compaction memory synchronization",
      "codigo abierto",
      "sistema de memoria",
      "busqueda hibrida",
      "decaimiento temporal",
      "compactacion",
      "sincronizacion de memoria",
    ],
    [
      {
        factId: "openclaw-memory-ranking",
        text: "Rodrigo contributed multiple merged changes to OpenClaw's memory system, implementing MMR re-ranking and temporal decay for hybrid search.",
        entities: ["Rodrigo Uroz", "OpenClaw", "MMR"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "openclaw-compaction-memory",
        text: "Rodrigo also strengthened OpenClaw's compaction safeguards and post-compaction transcript and memory synchronization.",
        entities: ["Rodrigo Uroz", "OpenClaw"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "leadership-capability",
    "capabilities",
    "Leadership · Capabilities",
    [
      "leadership",
      "team",
      "engineering teams",
      "hiring",
      "training",
      "mentoring",
      "delivery",
      "leadership lesson",
      "management principle",
      "people work to live",
      "liderazgo",
      "equipo",
      "contratar",
      "entrenar",
      "aprendizaje de liderazgo",
      "principio de liderazgo",
      "personas trabajan para vivir",
    ],
    [
      {
        factId: "leadership-build",
        text: "Rodrigo has built new teams and functions, including establishing DLA TV's first QA team.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "leadership-scale",
        text: "He has led a six-engineer team, managed about ten people across three cities, and grown a client engagement to roughly thirty people.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "leadership-people",
        text: "His leadership work includes hiring, training, mentoring, and defining delivery practices.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "leadership-progression",
        text: "He has moved between hands-on engineering, technical leadership, people management, and project leadership.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "leadership-work-serves-life",
        text: "A leadership lesson that changed how Rodrigo manages people is that people work to live; they do not live to work.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "technical-capabilities",
    "capabilities",
    "Technical capabilities",
    [
      "technical skills",
      "technology",
      "modernizing",
      "modernization",
      "monolith",
      "apis",
      "full stack",
      "react",
      "node",
      "php",
      "java",
      "csharp",
      "rails",
      "graphql",
      "realtime",
      "event driven",
      "cloud",
      "postgresql",
      "langfuse",
      "orchestrator",
      "working principles",
      "uncertainty",
      "uncertain capability",
      "test idea",
      "smallest experiment",
      "validation",
      "probes",
      "trade-offs",
      "principios de trabajo",
      "incertidumbre",
      "validacion",
      "llms",
      "decisions",
      "responsibility",
      "delegar decisiones",
      "habilidades tecnicas",
      "tecnologias",
    ],
    [
      {
        factId: "technical-fullstack",
        text: "Rodrigo has built frontend and backend systems with TypeScript, React, Node.js, PHP, Java, C#, and Rails.",
        entities: ["TypeScript", "React", "Node.js", "PHP", "Java", "C#", "Rails"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "technical-data",
        text: "He has worked with PostgreSQL, MySQL, Oracle, and Cloudflare D1.",
        entities: ["PostgreSQL", "MySQL", "Oracle", "Cloudflare D1"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "technical-architecture",
        text: "His architecture work includes legacy modernization, selective monolith decomposition, REST and GraphQL APIs, real-time coordination, and event-driven processing.",
        entities: ["REST", "GraphQL"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "technical-cloud",
        text: "He has operated software on AWS and Kubernetes and built independent products with Cloudflare Workers, Durable Objects, and D1.",
        entities: ["AWS", "Kubernetes", "Cloudflare Workers", "Durable Objects", "Cloudflare D1"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "technical-ai",
        text: "His LLM work spans product features, evaluation with Langfuse, model and orchestrator selection, realtime and multimodal APIs, coding agents, and custom skills.",
        entities: ["Langfuse", "LLMs"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "technical-ai-native",
        text: "Rodrigo uses LLMs, coding agents, and custom skills to accelerate work, while keeping product, architecture, and quality decisions his responsibility.",
        entities: ["Rodrigo Uroz", "LLMs"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "technical-integrations",
        text: "He has integrated third-party providers, IoT devices, incomplete APIs, and on-chain financial activity.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "technical-validation",
        text: "Rodrigo reduces uncertainty with the smallest credible experiment: a synthetic scenario, benchmark, throwaway probe, or test in the real device and environment where the product will run.",
        entities: ["Rodrigo Uroz", "Coro", "Ballast", "Jacara"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "international-work-profile",
    "capabilities",
    "International work profile",
    [
      "english",
      "spanish",
      "languages",
      "united states",
      "usa",
      "belgium",
      "visa",
      "b1",
      "b2",
      "buenos aires",
      "idiomas",
      "ingles",
      "espanol",
      "viajar",
    ],
    [
      {
        factId: "international-location-languages",
        text: "Spanish is Rodrigo's native language, and he works professionally in English.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "international-current-location",
        text: "As of August 25, 2026, Rodrigo is based in Buenos Aires, Argentina.",
        entities: ["Rodrigo Uroz", "Buenos Aires", "Argentina"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
      {
        factId: "international-clients",
        text: "Rodrigo has worked with United States clients for at least ten years and with a Belgian client in English.",
        entities: ["Rodrigo Uroz", "United States", "Belgium"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "international-visa",
        text: "As of August 25, 2026, Rodrigo holds a valid United States B1/B2 visa for permitted business travel; it is not work authorization.",
        entities: ["Rodrigo Uroz", "United States"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
      {
        factId: "international-flexibility",
        text: "As of August 25, 2026, Rodrigo is willing to discuss business travel, relocation, work authorization, or sponsorship with a prospective company.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
    ],
  ),
  source(
    "coro-product",
    "projects",
    "Coro · Independent project",
    [
      "coro",
      "coro.world",
      "global conversation",
      "language",
      "multilingual",
      "semantic routing",
      "realtime",
      "rooms",
      "topics",
      "follow graph",
      "conversaciones",
      "enrutamiento semantico",
    ],
    [
      {
        factId: "coro-purpose",
        text: "Coro explores whether relevant conversations can form around people across languages without rooms, channels, topics, or follower graphs.",
        entities: ["Coro"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "coro-routing",
        text: "Coro uses personalized, explainable semantic routing; translation is a separate representation layer rather than part of routing.",
        entities: ["Coro"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "coro-context",
        text: "Coro deterministically backfills the context needed for replies, quotes, and mentions.",
        entities: ["Coro"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "coro-features",
        text: "The product supports progressive identity, real-time conversation, moderation, Web Push, and private history.",
        entities: ["Coro"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "coro-stack",
        text: "Coro uses React and Vite, Hono on Cloudflare Workers, Durable Objects for real-time coordination, D1 for persistence, and model adapters through an AI Gateway.",
        entities: ["Coro", "React", "Vite", "Hono", "Cloudflare Workers", "Durable Objects", "D1"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "coro-architecture",
        text: "Coro separates contracts, domain logic, application code, and simulation infrastructure.",
        entities: ["Coro"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "coro-simulation-lab",
        text: "Its simulation lab runs the production routing logic against synthetic scenarios.",
        entities: ["Coro"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "coro-ownership",
        text: "Rodrigo founded Coro and is its only builder.",
        entities: ["Rodrigo Uroz", "Coro"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "coro-url",
        text: "As of August 25, 2026, Coro is available at https://coro.world.",
        entities: ["Coro"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
    ],
  ),
  source(
    "traza-product",
    "projects",
    "Traza · Independent project",
    [
      "traza",
      "financial activity",
      "finance",
      "reconciliation",
      "privacy",
      "cloudflare",
      "wallbit",
      "transactions",
      "transfers",
      "investments",
      "tron",
      "usdt",
      "privacidad",
      "finanzas",
    ],
    [
      {
        factId: "traza-purpose",
        text: "Traza organizes fragmented financial activity into a traceable history of income, expenses, transfers, and investments.",
        entities: ["Traza"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-motivation",
        text: "Rodrigo built Traza because transaction lists do not explain how money moved; the product keeps evidence, uncertainty, and review history visible.",
        entities: ["Rodrigo Uroz", "Traza"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-domain",
        text: "Traza uses a provider-independent canonical financial domain model, with transaction intent, entity, and category represented separately.",
        entities: ["Traza"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-wallbit-sync",
        text: "Traza's Wallbit connector is read-only and preserves synchronization history.",
        entities: ["Traza", "Wallbit"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-enrichment",
        text: "Traza runs deterministic, public-data, and model-backed enrichment behind an explicit privacy boundary.",
        entities: ["Traza"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-corrections",
        text: "User corrections remain private; only non-private public knowledge can be reused.",
        entities: ["Traza"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-onchain",
        text: "Traza reconciles on-chain activity, including TRON USDT withdrawals, with provider activity.",
        entities: ["Traza", "TRON", "USDT"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-stack",
        text: "Traza uses React, Vite, and TypeScript with a Cloudflare Worker and D1 backend.",
        entities: ["Traza", "React", "Vite", "TypeScript", "Cloudflare Workers", "D1"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-provider-boundary",
        text: "Provider-specific behavior is isolated, and provider payloads and credentials are not exposed to the browser.",
        entities: ["Traza"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-ownership",
        text: "Rodrigo founded Traza and is its only builder.",
        entities: ["Rodrigo Uroz", "Traza"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "traza-url",
        text: "As of August 25, 2026, Traza is available at https://traza.rodrigouroz.com.",
        entities: ["Traza"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
    ],
  ),
  source(
    "daturno-product",
    "projects",
    "Daturno · Independent product",
    [
      "daturno",
      "whatsapp scheduling",
      "appointments",
      "reservations",
      "booking rules",
      "availability",
      "conversational assistant",
      "bounded ai",
      "public registration",
      "publicly available",
      "sole builder",
      "back office",
      "production telemetry",
      "customer count",
      "agenda por whatsapp",
      "turnos",
      "reservas",
      "reglas de agenda",
      "disponibilidad",
      "asistente conversacional",
      "ia acotada",
      "registro publico",
      "disponible publicamente",
      "unico builder",
      "backoffice",
      "telemetria de produccion",
      "cantidad de clientes",
    ],
    [
      {
        factId: "daturno-purpose",
        text: "Daturno is a WhatsApp-first scheduling product for businesses, professionals, and institutions that coordinates appointments and reservations through a conversational assistant and an administration panel.",
        entities: ["Daturno", "WhatsApp"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "daturno-bounded-ai",
        text: "Daturno combines a deterministic engine that owns availability and booking rules with a model that interprets the conversational user interface and extracts structured intent and details.",
        entities: ["Daturno", "WhatsApp", "LLMs"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "daturno-ownership",
        text: "Rodrigo designed and built Daturno end to end and is its only builder.",
        entities: ["Rodrigo Uroz", "Daturno"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "daturno-motivation",
        text: "Rodrigo explored product ideas and chose scheduling to address the operational agenda needs of businesses that manage appointments or reservations.",
        entities: ["Rodrigo Uroz", "Daturno"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "daturno-operation",
        text: "He took Daturno from product definition and domain modeling to a deployed API, business dashboard, and internal back office with production telemetry and operational observability.",
        entities: ["Rodrigo Uroz", "Daturno"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "daturno-maturity",
        text: "As of August 25, 2026, Daturno is publicly available for businesses to register and use, with a 30-day trial and a paid monthly subscription.",
        entities: ["Daturno"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
      {
        factId: "daturno-url",
        text: "As of August 25, 2026, Daturno is publicly available at https://daturno.com.",
        entities: ["Daturno"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
    ],
  ),
  source(
    "ballast-product",
    "projects",
    "Ballast · Independent project",
    [
      "ballast",
      "portfolio",
      "monte carlo",
      "optimization",
      "genetic optimizer",
      "tax lot",
      "fees",
      "taxes",
      "validation lab",
      "broker independent",
      "supuestos",
      "portafolio",
      "optimizacion",
    ],
    [
      {
        factId: "ballast-purpose",
        text: "Ballast is a broker-independent tool for exploring investment plans from explicit assumptions.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-motivation",
        text: "Rodrigo built Ballast to keep a portfolio model's assumptions, allocations, uncertainty, and trade-offs visible instead of presenting a black-box recommendation.",
        entities: ["Rodrigo Uroz", "Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-experience",
        text: "A user chooses a strategy, investment amount, target, and assumptions, then compares outcome ranges, drawdowns, and required monthly contributions.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-simulation",
        text: "Ballast runs Monte Carlo simulations locally in the browser.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-optimizer",
        text: "A genetic optimizer searches for alternative plans; exact simulation then verifies the candidates.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-financial-model",
        text: "Ballast's optimization model includes tax-lot reconciliation and explicit fee and tax rules.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-data-normalization",
        text: "Ballast normalizes provider data before it reaches the optimization model.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-validation",
        text: "Its Validation Lab uses versioned datasets, point-in-time cuts, leakage-free validation, and auditable diagnostics.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-stack",
        text: "Ballast uses React, Vite, TypeScript, Hono on Cloudflare Workers, and D1.",
        entities: ["Ballast", "React", "Vite", "TypeScript", "Hono", "Cloudflare Workers", "D1"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-boundaries",
        text: "Ballast does not predict markets, execute trades, or present itself as financial advice.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-ownership",
        text: "Rodrigo founded Ballast and is its only builder.",
        entities: ["Rodrigo Uroz", "Ballast"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "ballast-url",
        text: "As of August 25, 2026, Ballast is publicly available at https://ballast.rodrigouroz.com.",
        entities: ["Ballast"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
    ],
  ),
  source(
    "jacara-product",
    "projects",
    "Jacara · Independent project",
    [
      "jacara",
      "tiny adventures",
      "family game",
      "physical-first",
      "computer vision",
      "voice",
      "nara",
      "object hunt",
      "iphone",
      "yaml",
      "camera",
      "microphone",
      "familia",
      "juego",
      "pantallas",
    ],
    [
      {
        factId: "jacara-purpose",
        text: "Jacara is the user-facing name of a physical-first family game system guided in the browser by Nara; Tiny Adventures was an earlier internal name.",
        entities: ["Jacara", "Tiny Adventures", "Nara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-motivation",
        text: "Rodrigo built Jacara around shared family play rather than isolated time on separate screens.",
        entities: ["Rodrigo Uroz", "Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-phone-role",
        text: "The phone gives instructions and senses selected actions, but the play happens among people and their surroundings.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-audience-mechanics",
        text: "The indoor experience is designed for two to six players ages five and older, with object hunts, rhythm, laughter, voice echo, drawing, and visual-memory activities.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-narrative",
        text: "Jacara's stories include player decisions and fail-forward outcomes.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-pipeline",
        text: "A compiler turns versioned YAML game content into the runtime's canonical abstract syntax tree.",
        entities: ["Jacara", "YAML"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-capabilities",
        text: "Jacara separates game mechanics from browser capabilities and enables a capability only after focused probes and physical tests support it.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-audio",
        text: "Jacara pre-generates and validates its narration audio.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-audio-storage",
        text: "Narration files are content-addressed, while real-time model audio is reserved for mechanics that explicitly require it.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-privacy",
        text: "Jacara bounds camera and microphone access to the mechanics that need them and degrades conservatively when a capability is unavailable.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-media-retention",
        text: "Jacara does not retain player photos or audio by default.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-stack",
        text: "Jacara uses React, Vite, TypeScript, OpenCV.js, Cloudflare Workers, and OpenAI adapters.",
        entities: ["Jacara", "React", "Vite", "TypeScript", "OpenCV.js", "Cloudflare Workers"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-validation",
        text: "Jacara's acceptance work includes real-iPhone checks and physical family playtests; a successful browser build is not sufficient.",
        entities: ["Jacara", "iPhone"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-ownership",
        text: "Rodrigo designed Jacara and is its only builder.",
        entities: ["Rodrigo Uroz", "Jacara"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "jacara-url",
        text: "As of August 25, 2026, Jacara is available at https://jacara.rodrigouroz.com.",
        entities: ["Jacara"],
        reviewedAt: "2026-08-25",
        expiresAt: "2026-11-25",
      },
    ],
  ),
  source(
    "utn-education-and-teaching",
    "education",
    "UTN · Education and teaching",
    [
      "utn",
      "systems engineer",
      "degree",
      "completed degree",
      "titulo universitario",
      "education",
      "professor",
      "teaching",
      "systems analysis",
      "operative systems",
      "universidad tecnologica nacional",
      "ingeniero en sistemas",
      "docente",
      "analisis de sistemas",
      "sistemas operativos",
      "teaching engineering",
      "teaching experience and engineering work",
      "requirements explanation",
      "domain models",
      "docencia e ingenieria",
      "experiencia docente y trabajo como ingeniero",
      "explicar requisitos",
      "modelos de dominio",
    ],
    [
      {
        factId: "utn-degree",
        text: "Rodrigo earned his Systems Engineering degree from Universidad Tecnológica Nacional (UTN) in March 2009.",
        entities: ["Rodrigo Uroz", "UTN"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "utn-teaching-period",
        text: "Rodrigo taught at UTN from 2003 through 2021.",
        entities: ["Rodrigo Uroz", "UTN"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "utn-systems-analysis",
        text: "For most of those eighteen years, he taught Systems Analysis as an Adjunct Professor.",
        entities: ["Rodrigo Uroz", "UTN", "Systems Analysis"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "utn-systems-analysis-content",
        text: "His Systems Analysis course covered software lifecycles, planning, requirements elicitation, UML, and data modeling.",
        entities: ["Rodrigo Uroz", "UTN", "Systems Analysis"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "utn-teaching-engineering-connection",
        text: "His teaching experience complements his engineering work with a long practice of explaining requirements, domain models, and system design.",
        entities: ["Rodrigo Uroz", "UTN", "Systems Analysis"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "utn-operative-systems",
        text: "He was a Teaching Assistant in Sistemas Operativos (Operating Systems) only during the first two or three years of his teaching career.",
        entities: ["Rodrigo Uroz", "UTN", "Sistemas Operativos", "Operating Systems"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "utn-operative-wording",
        text: "The original course name is Sistemas Operativos; its idiomatic English translation is Operating Systems.",
        entities: ["UTN", "Sistemas Operativos", "Operating Systems"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "itba-eoi-coursework",
    "education",
    "ITBA–EOI · Education",
    [
      "itba",
      "eoi",
      "graduate",
      "coursework",
      "thesis",
      "strategic management",
      "posgrado",
      "tesis",
    ],
    [
      {
        factId: "itba-coursework",
        text: "Rodrigo completed the coursework for a graduate program in Strategic and Technological Management at ITBA–EOI.",
        entities: ["Rodrigo Uroz", "ITBA", "EOI"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "itba-no-degree",
        text: "He did not submit the thesis and therefore did not earn the graduate degree.",
        entities: ["Rodrigo Uroz", "ITBA", "EOI"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "silver-mentoring",
    "capabilities",
    "Silver.dev · Mentoring",
    ["silver", "mentor", "mentoring", "live coding", "system design", "full stack", "mentoria"],
    [
      {
        factId: "silver-role-topics",
        text: "Through Silver.dev, Rodrigo mentors candidates in full-stack live coding and system design.",
        entities: ["Rodrigo Uroz", "Silver.dev"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "historical-independent-projects",
    "projects",
    "Earlier independent projects",
    [
      "ask holidays",
      "wit ai",
      "housing scraper",
      "telegram",
      "pami",
      "fabric cutting",
      "simulated annealing",
      "rent a coder",
      "vworker",
      "proyectos anteriores",
    ],
    [
      {
        factId: "historical-ask-holidays",
        text: "Ask Holidays was a Next.js application that used Wit.ai for natural-language holiday queries.",
        entities: ["Ask Holidays", "Next.js", "Wit.ai"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "historical-housing",
        text: "Rodrigo built a Python housing scraper that detected new listings and sent Telegram notifications.",
        entities: ["Rodrigo Uroz", "Python", "Telegram"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "historical-pami",
        text: "Rodrigo built a pharmacy system for PAMI with Java, JSF, Hibernate, and MySQL.",
        entities: ["Rodrigo Uroz", "PAMI", "Java", "JSF", "Hibernate", "MySQL"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "historical-cutting",
        text: "Rodrigo built a fabric-cutting optimizer in Python and PyGTK using simulated annealing and other heuristics.",
        entities: ["Rodrigo Uroz", "Python", "PyGTK"],
        reviewedAt: "2026-08-25",
      },
      {
        factId: "historical-vworker",
        text: "Rodrigo spent roughly three years completing freelance projects through Rent a Coder and VWorker, using PHP, Java, Visual Basic, and C.",
        entities: ["Rodrigo Uroz", "Rent a Coder", "VWorker", "PHP", "Java", "Visual Basic", "C"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
  source(
    "personal-background",
    "about",
    "Beyond work",
    [
      "hobbies",
      "interests",
      "piano",
      "reading",
      "chess",
      "video games",
      "pasatiempos",
      "intereses",
      "lectura",
      "ajedrez",
      "videojuegos",
    ],
    [
      {
        factId: "personal-interests",
        text: "Outside work, Rodrigo enjoys playing piano, reading, chess, and video games.",
        entities: ["Rodrigo Uroz"],
        reviewedAt: "2026-08-25",
      },
    ],
  ),
];

validateCorpus(assistantCorpus);

export function getCurrentAssistantCorpus(today: IsoDate) {
  return currentCorpus(assistantCorpus, today);
}
