import type { CanonicalEvidence, CanonicalFact, SectionId } from "./contracts";

const REVIEWED_AT = "2026-08-25" as const;
type FactInput = readonly [
  factId: string,
  text: string,
  entities: readonly string[],
  claimTypes: readonly string[],
];

function source(
  sourceId: string,
  sectionId: SectionId,
  title: string,
  searchTerms: readonly string[],
  inputs: readonly FactInput[],
): CanonicalEvidence {
  const facts: CanonicalFact[] = inputs.map(([factId, text, entities, claimTypes]) => ({
    factId,
    text,
    entities,
    claimTypes,
    status: "approved",
    reviewedAt: REVIEWED_AT,
  }));
  return {
    sourceId,
    sectionId,
    canonicalLanguage: "en",
    title,
    status: "approved",
    reviewedAt: REVIEWED_AT,
    searchTerms,
    facts,
  };
}

export const assistantCorpus: readonly CanonicalEvidence[] = [
  source(
    "assistant-identity",
    "about",
    "Ask Rodrigo · Assistant identity and boundaries",
    ["assistant", "name", "alfred", "identity", "nombre", "asistente", "como te llamas"],
    [
      [
        "assistant-identity-name",
        "The assistant is called Alfred when a visitor asks for its name.",
        ["Alfred", "Ask Rodrigo"],
        ["identity"],
      ],
      [
        "assistant-identity-not-rodrigo",
        "Alfred is Rodrigo Uroz's professional assistant and must never claim to be Rodrigo.",
        ["Alfred", "Rodrigo Uroz"],
        ["identity", "boundary"],
      ],
      [
        "assistant-identity-public-only",
        "Alfred answers only from Rodrigo's public, curated, approved corpus and never consults private repositories.",
        ["Alfred", "Ask Rodrigo"],
        ["grounding", "privacy"],
      ],
      [
        "assistant-identity-fallback",
        "When approved evidence is insufficient, Alfred offers a way to contact Rodrigo instead of inferring an answer.",
        ["Alfred", "Rodrigo Uroz"],
        ["grounding", "contact"],
      ],
    ],
  ),
  source(
    "career-overview",
    "experience",
    "Professional experience overview",
    [
      "career",
      "professional experience",
      "work history",
      "companies",
      "roles",
      "trayectoria",
      "experiencia profesional",
      "empresas",
    ],
    [
      [
        "career-years",
        "Rodrigo has more than 25 years of professional experience in software and product engineering.",
        ["Rodrigo Uroz"],
        ["tenure", "positioning"],
      ],
      [
        "career-positioning",
        "Rodrigo is a software engineer and product builder who turns ambiguous problems into real products and operating systems.",
        ["Rodrigo Uroz"],
        ["positioning", "capability"],
      ],
      [
        "career-end-to-end",
        "His work spans product definition, domain modeling, architecture, implementation, deployment, and iteration.",
        ["Rodrigo Uroz"],
        ["capability"],
      ],
      [
        "career-companies",
        "His public career history includes ClassDojo, SCVSoft, Medallia, FutureAdvisor through SCVSoft, VSKO, DLA TV, OpenEnglish through TeraCode, Bumeran, Globant, and Claxson.",
        [
          "ClassDojo",
          "SCVSoft",
          "Medallia",
          "FutureAdvisor",
          "VSKO",
          "DLA TV",
          "OpenEnglish",
          "TeraCode",
          "Bumeran",
          "Globant",
          "Claxson",
        ],
        ["employment"],
      ],
      [
        "career-roles",
        "He has worked as an individual contributor, Tech Lead, Lead Software Engineer, Senior Engineering Manager, Head of Development, and Project Manager.",
        ["Rodrigo Uroz"],
        ["role", "leadership"],
      ],
      [
        "career-openness",
        "Rodrigo is open to roles, collaborations, and product conversations when the company, industry, or problem is compelling; he is not limited to a specific industry.",
        ["Rodrigo Uroz"],
        ["availability", "preference"],
      ],
    ],
  ),
  source(
    "classdojo-current-role",
    "experience",
    "ClassDojo · Experience",
    [
      "classdojo",
      "fullstack",
      "typescript",
      "monorepo",
      "zoom",
      "llm",
      "langfuse",
      "conductor",
      "aws",
      "kubernetes",
      "developer experience",
      "experiencia de desarrollo",
    ],
    [
      [
        "classdojo-role-period",
        "Rodrigo has worked at ClassDojo since January 1, 2022 as a Fullstack Software Engineer.",
        ["Rodrigo Uroz", "ClassDojo"],
        ["employment", "date", "role"],
      ],
      [
        "classdojo-typescript",
        "He helped migrate ClassDojo's web monorepo to TypeScript.",
        ["Rodrigo Uroz", "ClassDojo", "TypeScript"],
        ["implementation", "modernization"],
      ],
      [
        "classdojo-external-product",
        "His team inherited a product built outside the company and integrated it into ClassDojo's architecture.",
        ["Rodrigo Uroz", "ClassDojo"],
        ["integration", "architecture"],
      ],
      [
        "classdojo-zoom",
        "That product integration included third-party services such as Zoom for organizing classes.",
        ["ClassDojo", "Zoom"],
        ["integration", "implementation"],
      ],
      [
        "classdojo-llms",
        "Rodrigo was involved from the beginning in introducing LLMs into ClassDojo's product and development process through several features.",
        ["Rodrigo Uroz", "ClassDojo", "LLMs"],
        ["ai", "product"],
      ],
      [
        "classdojo-langfuse",
        "His LLM work at ClassDojo has included Langfuse.",
        ["Rodrigo Uroz", "ClassDojo", "Langfuse"],
        ["ai", "implementation"],
      ],
      [
        "classdojo-orchestrators",
        "He continuously evaluates new LLMs and orchestrators; he currently uses Conductor but changes tools as the space evolves.",
        ["Rodrigo Uroz", "Conductor", "LLMs"],
        ["ai", "practice"],
      ],
      [
        "classdojo-skills-dx",
        "ClassDojo's development practice includes many in-house agent skills, and Rodrigo focuses on adopting technologies that improve developer experience.",
        ["Rodrigo Uroz", "ClassDojo"],
        ["ai", "developer-experience"],
      ],
      [
        "classdojo-cloud",
        "He has extensive production experience with AWS and Kubernetes, including their use at ClassDojo.",
        ["Rodrigo Uroz", "ClassDojo", "AWS", "Kubernetes"],
        ["cloud", "infrastructure"],
      ],
    ],
  ),
  source(
    "scvsoft-iot-tech-lead",
    "experience",
    "SCVSoft · Experience",
    [
      "scvsoft",
      "iot",
      "tech lead",
      "third-party api",
      "reverse engineering",
      "hotels",
      "buildings",
      "dispositivos",
      "ingenieria inversa",
    ],
    [
      [
        "scvsoft-period-role",
        "Rodrigo worked at SCVSoft from July through December 2021 as a Tech Lead.",
        ["Rodrigo Uroz", "SCVSoft"],
        ["employment", "date", "role"],
      ],
      [
        "scvsoft-client",
        "He worked for an anonymous B2B IoT client serving large hotels, buildings, and similar facilities.",
        ["Rodrigo Uroz", "SCVSoft"],
        ["client", "domain"],
      ],
      [
        "scvsoft-aggregator",
        "The service aggregated providers and APIs behind one interface independent of the devices in use.",
        ["SCVSoft"],
        ["architecture", "integration"],
      ],
      [
        "scvsoft-reverse-engineering",
        "Rodrigo reverse-engineered some devices because their APIs were poorly documented or confusing.",
        ["Rodrigo Uroz", "SCVSoft"],
        ["reverse-engineering", "integration"],
      ],
    ],
  ),
  source(
    "medallia-engineering-management",
    "experience",
    "Medallia · Experience",
    [
      "medallia",
      "engineering manager",
      "frontend team",
      "angular",
      "react",
      "redux",
      "graphql",
      "leadership",
      "equipo frontend",
    ],
    [
      [
        "medallia-period-role",
        "Rodrigo worked at Medallia from December 2018 through July 2021 as a Senior Engineering Manager.",
        ["Rodrigo Uroz", "Medallia"],
        ["employment", "date", "role"],
      ],
      [
        "medallia-team",
        "He led a frontend team of about ten people distributed across three cities.",
        ["Rodrigo Uroz", "Medallia"],
        ["leadership", "team"],
      ],
      [
        "medallia-modernization",
        "His team modernized seven legacy Angular applications into React and Redux applications.",
        ["Medallia", "Angular", "React", "Redux"],
        ["modernization", "implementation"],
      ],
      [
        "medallia-graphql",
        "The modernization included moving client integration from REST toward GraphQL.",
        ["Medallia", "REST", "GraphQL"],
        ["architecture", "modernization"],
      ],
      [
        "medallia-scale",
        "The products his team worked on were used by thousands of Medallia customers.",
        ["Medallia"],
        ["product-scale"],
      ],
    ],
  ),
  source(
    "futureadvisor-lead-engineer",
    "experience",
    "FutureAdvisor / SCVSoft · Experience",
    [
      "futureadvisor",
      "scvsoft",
      "lead engineer",
      "rails",
      "postgresql",
      "react",
      "redux",
      "aws",
      "sqs",
      "sns",
      "batch",
      "lambda",
      "portfolio",
    ],
    [
      [
        "futureadvisor-period-role",
        "Rodrigo worked on FutureAdvisor through SCVSoft from September 2016 through December 2018 as a Lead Software Engineer.",
        ["Rodrigo Uroz", "FutureAdvisor", "SCVSoft"],
        ["employment", "date", "role"],
      ],
      [
        "futureadvisor-team",
        "He led a six-engineer team.",
        ["Rodrigo Uroz", "FutureAdvisor"],
        ["leadership", "team"],
      ],
      [
        "futureadvisor-stack",
        "The system used a Rails and PostgreSQL backend with a React and Redux frontend.",
        ["FutureAdvisor", "Rails", "PostgreSQL", "React", "Redux"],
        ["implementation", "technology"],
      ],
      [
        "futureadvisor-services",
        "The team evolved a monolith toward AWS services including SQS, SNS, Batch, and Lambda.",
        ["FutureAdvisor", "AWS", "SQS", "SNS", "Batch", "Lambda"],
        ["architecture", "modernization", "cloud"],
      ],
      [
        "futureadvisor-outcome",
        "A daily processing workflow was reduced from about three hours to about fifty minutes while its cost was reduced by about half.",
        ["FutureAdvisor"],
        ["performance", "cost", "outcome"],
      ],
    ],
  ),
  source(
    "vsko-education-software",
    "experience",
    "Lemonade / VSKO · Experience",
    [
      "lemonade",
      "vsko",
      "belgian",
      "belgium",
      "catholic schools",
      "education software",
      "java",
      "jersey",
      "google api",
      "node",
      "angularjs",
    ],
    [
      [
        "vsko-period-role",
        "Rodrigo worked on VSKO through Lemonade from 2013 to 2016 as a Software Engineer.",
        ["Rodrigo Uroz", "VSKO", "Lemonade"],
        ["employment", "date", "role"],
      ],
      [
        "vsko-product",
        "He built classroom and administration software for Catholic schools in Belgium.",
        ["Rodrigo Uroz", "VSKO"],
        ["product", "domain"],
      ],
      [
        "vsko-stack",
        "The implementation included Java and Jersey, Google APIs, PostgreSQL, MySQL, Node, Express, Passport, and AngularJS.",
        ["VSKO", "Java", "Jersey", "PostgreSQL", "MySQL", "Node.js", "AngularJS"],
        ["implementation", "technology"],
      ],
      [
        "vsko-english",
        "Rodrigo communicated with the Belgian client in English.",
        ["Rodrigo Uroz", "VSKO"],
        ["language", "client"],
      ],
    ],
  ),
  source(
    "dla-team-and-qa",
    "experience",
    "DLA TV · Experience",
    [
      "dla",
      "head of development",
      "qa",
      "team building",
      "hiring",
      "training",
      "delivery process",
      "equipo",
      "contratacion",
    ],
    [
      [
        "dla-period-role",
        "Rodrigo worked at DLA TV from 2012 to 2013 as Head of Development.",
        ["Rodrigo Uroz", "DLA TV"],
        ["employment", "date", "role"],
      ],
      [
        "dla-qa",
        "He created the QA team from scratch because the organization did not have one.",
        ["Rodrigo Uroz", "DLA TV"],
        ["leadership", "team-building", "quality"],
      ],
      [
        "dla-growth",
        "He expanded the development team, hired and trained people, and defined engineering and delivery processes.",
        ["Rodrigo Uroz", "DLA TV"],
        ["leadership", "hiring", "training", "process"],
      ],
    ],
  ),
  source(
    "openenglish-engagement",
    "experience",
    "TeraCode / OpenEnglish · Experience",
    [
      "teracode",
      "openenglish",
      "project manager",
      "individual contributor",
      "30 people",
      "ic",
      "gerente de proyecto",
    ],
    [
      [
        "openenglish-period",
        "Rodrigo worked on OpenEnglish through TeraCode from 2009 to 2012; OpenEnglish was a client, not his employer.",
        ["Rodrigo Uroz", "OpenEnglish", "TeraCode"],
        ["employment", "date", "client"],
      ],
      [
        "openenglish-progression",
        "He started as an individual contributor, later became Project Manager, and grew the engagement to roughly thirty people.",
        ["Rodrigo Uroz", "OpenEnglish", "TeraCode"],
        ["role", "leadership", "scale"],
      ],
    ],
  ),
  source(
    "bumeran-search",
    "experience",
    "Bumeran · Experience",
    ["bumeran", "php", "java", "solr", "search engine", "resumes", "cvs", "buscador"],
    [
      [
        "bumeran-period-role",
        "Rodrigo worked at Bumeran from 2007 to 2009 as a Software Engineer.",
        ["Rodrigo Uroz", "Bumeran"],
        ["employment", "date", "role"],
      ],
      [
        "bumeran-stack-search",
        "He worked on a PHP backend and implemented a Java and Solr search engine over candidate resumes.",
        ["Rodrigo Uroz", "Bumeran", "PHP", "Java", "Solr"],
        ["implementation", "search"],
      ],
    ],
  ),
  source(
    "globant-functional-analysis",
    "experience",
    "Globant · Experience",
    ["globant", "functional analyst", "marketplace", "refactor", "analisis funcional"],
    [
      [
        "globant-period-role",
        "Rodrigo worked at Globant from 2006 to 2007 as a Functional Analyst.",
        ["Rodrigo Uroz", "Globant"],
        ["employment", "date", "role"],
      ],
      [
        "globant-marketplace",
        "He led functional analysis for a marketplace refactor.",
        ["Rodrigo Uroz", "Globant"],
        ["analysis", "leadership", "modernization"],
      ],
    ],
  ),
  source(
    "mixplay-streaming",
    "experience",
    "Claxson / Mixplay · Experience",
    ["claxson", "mixplay", "streaming", "php", "oracle", "csharp", "drm", "encryption"],
    [
      [
        "mixplay-period-role",
        "Rodrigo worked at Claxson on Mixplay from 2003 to 2006 as a Senior Developer.",
        ["Rodrigo Uroz", "Claxson", "Mixplay"],
        ["employment", "date", "role"],
      ],
      [
        "mixplay-platform",
        "He built a streaming platform with PHP, Oracle, C#, DRM, and content encryption.",
        ["Rodrigo Uroz", "Mixplay", "PHP", "Oracle", "C#", "DRM"],
        ["product", "implementation", "security"],
      ],
    ],
  ),
  source(
    "product-engineering-capability",
    "capabilities",
    "Product engineering · Capabilities",
    [
      "product engineer",
      "software engineer",
      "zero to one",
      "developer experience",
      "25 years",
      "end to end",
      "ambiguity",
      "producto",
      "ambiguedad",
    ],
    [
      [
        "product-zero-to-one",
        "Rodrigo has repeatedly taken products from zero to one and turned ambiguous product and domain problems into working software.",
        ["Rodrigo Uroz"],
        ["capability", "product", "domain-modeling"],
      ],
      [
        "product-operation",
        "He works across product definition, architecture, implementation, deployment, operations, and iteration.",
        ["Rodrigo Uroz"],
        ["capability", "product", "engineering"],
      ],
      [
        "product-project-examples",
        "Coro, Traza, Ballast, and Jacara are examples of products he designed and built end-to-end by himself.",
        ["Rodrigo Uroz", "Coro", "Traza", "Ballast", "Jacara"],
        ["capability", "project", "ownership"],
      ],
    ],
  ),
  source(
    "leadership-capability",
    "capabilities",
    "Leadership · Capabilities",
    [
      "leadership",
      "team",
      "engineering teams",
      "hiring",
      "training",
      "mentoring",
      "delivery",
      "liderazgo",
      "equipo",
      "contratar",
      "entrenar",
    ],
    [
      [
        "leadership-build",
        "Rodrigo has built teams from scratch, including creating a QA function where none existed.",
        ["Rodrigo Uroz"],
        ["leadership", "team-building", "quality"],
      ],
      [
        "leadership-scale",
        "He has expanded engineering teams and led groups ranging from six engineers to engagements of roughly thirty people.",
        ["Rodrigo Uroz"],
        ["leadership", "team", "scale"],
      ],
      [
        "leadership-people",
        "He has hired, trained, and mentored engineers and defined engineering and delivery processes.",
        ["Rodrigo Uroz"],
        ["leadership", "hiring", "training", "mentoring", "process"],
      ],
      [
        "leadership-progression",
        "His career includes transitions from individual contributor work into technical, people, and project leadership.",
        ["Rodrigo Uroz"],
        ["leadership", "role"],
      ],
    ],
  ),
  source(
    "technical-capabilities",
    "capabilities",
    "Technical capabilities",
    [
      "technical skills",
      "technology",
      "full stack",
      "react",
      "node",
      "php",
      "java",
      "csharp",
      "rails",
      "graphql",
      "realtime",
      "event driven",
      "cloud",
      "postgresql",
      "langfuse",
      "orchestrator",
      "habilidades tecnicas",
      "tecnologias",
    ],
    [
      [
        "technical-fullstack",
        "Rodrigo's full-stack experience includes TypeScript, React, Node.js, PHP, Java, C#, and Rails.",
        ["TypeScript", "React", "Node.js", "PHP", "Java", "C#", "Rails"],
        ["capability", "technology"],
      ],
      [
        "technical-data",
        "His database experience includes PostgreSQL, MySQL, Oracle, and Cloudflare D1.",
        ["PostgreSQL", "MySQL", "Oracle", "Cloudflare D1"],
        ["capability", "technology", "data"],
      ],
      [
        "technical-architecture",
        "His architecture experience includes legacy modernization, monolith-to-services evolution, REST, GraphQL, real-time systems, and event-driven systems.",
        ["REST", "GraphQL"],
        ["capability", "architecture", "modernization"],
      ],
      [
        "technical-cloud",
        "His cloud experience includes AWS, Kubernetes, Cloudflare Workers, Durable Objects, and D1.",
        ["AWS", "Kubernetes", "Cloudflare Workers", "Durable Objects", "Cloudflare D1"],
        ["capability", "cloud", "infrastructure"],
      ],
      [
        "technical-ai",
        "His AI development experience includes LLM product features, Langfuse, multiple models and orchestrators, Realtime and multimodal APIs, coding agents, and custom skills.",
        ["Langfuse", "LLMs"],
        ["capability", "ai"],
      ],
      [
        "technical-ai-native",
        "Rodrigo uses coding agents, LLMs, and custom skills as force multipliers while retaining responsibility for product decisions, architecture, quality, and outcomes.",
        ["Rodrigo Uroz", "LLMs"],
        ["capability", "ai", "positioning"],
      ],
      [
        "technical-integrations",
        "His integration work includes third-party providers, IoT devices, poorly documented APIs, and on-chain financial activity.",
        ["Rodrigo Uroz"],
        ["capability", "integration", "reverse-engineering"],
      ],
      [
        "technical-validation",
        "He validates uncertain systems with simulations, benchmarks, throwaway probes, privacy gates, and physical-device testing when appropriate.",
        ["Rodrigo Uroz"],
        ["capability", "quality", "validation"],
      ],
    ],
  ),
  source(
    "international-work-profile",
    "capabilities",
    "International work profile",
    [
      "english",
      "spanish",
      "languages",
      "united states",
      "usa",
      "belgium",
      "visa",
      "b1",
      "b2",
      "buenos aires",
      "idiomas",
      "ingles",
      "espanol",
      "viajar",
    ],
    [
      [
        "international-location-languages",
        "Rodrigo is based in Buenos Aires, Argentina; Spanish is his native language and he works professionally in English.",
        ["Rodrigo Uroz", "Buenos Aires", "Argentina"],
        ["location", "language"],
      ],
      [
        "international-clients",
        "He has worked for clients in the United States for at least ten years and worked in English with a Belgian client.",
        ["Rodrigo Uroz", "United States", "Belgium"],
        ["client", "international", "language"],
      ],
      [
        "international-visa",
        "Rodrigo holds a valid United States B1/B2 visa for permitted business travel; it is not United States work authorization.",
        ["Rodrigo Uroz", "United States"],
        ["travel", "visa", "boundary"],
      ],
      [
        "international-flexibility",
        "He can discuss occasional international business travel, relocation, employment authorization, or sponsorship directly with a prospective company.",
        ["Rodrigo Uroz"],
        ["travel", "availability", "boundary"],
      ],
    ],
  ),
  source(
    "coro-product",
    "projects",
    "Coro · Independent project",
    [
      "coro",
      "coro.world",
      "global conversation",
      "language",
      "multilingual",
      "semantic routing",
      "realtime",
      "rooms",
      "topics",
      "follow graph",
      "conversaciones",
      "enrutamiento semantico",
    ],
    [
      [
        "coro-purpose",
        "Coro explores whether relevant conversations can form naturally around people across languages, without rooms, topics, channels, or follower graphs.",
        ["Coro"],
        ["project", "motivation", "product"],
      ],
      [
        "coro-routing",
        "It uses personalized, explainable semantic routing, while multilingual translation remains a separate representation layer.",
        ["Coro"],
        ["project", "architecture", "ai", "language"],
      ],
      [
        "coro-context",
        "Coro deterministically backfills the context needed for replies, quotes, and mentions.",
        ["Coro"],
        ["project", "architecture", "implementation"],
      ],
      [
        "coro-features",
        "The product includes progressive identity, real-time conversation, moderation, Web Push, and private history.",
        ["Coro"],
        ["project", "product"],
      ],
      [
        "coro-stack",
        "Coro uses React and Vite, Hono on Cloudflare Workers, Durable Objects for real-time coordination, D1 for persistence, and model adapters through an AI Gateway.",
        ["Coro", "React", "Vite", "Hono", "Cloudflare Workers", "Durable Objects", "D1"],
        ["project", "implementation", "technology"],
      ],
      [
        "coro-architecture",
        "Its codebase separates contracts, domain, application, and simulation layers and includes a laboratory that runs the real router over synthetic scenarios.",
        ["Coro"],
        ["project", "architecture", "validation"],
      ],
      [
        "coro-ownership",
        "Rodrigo is Coro's founder and sole builder; he defined the product, domain model, and architecture and implemented, deployed, and iterated the complete system end-to-end.",
        ["Rodrigo Uroz", "Coro"],
        ["project", "ownership", "role"],
      ],
      ["coro-url", "Coro is available at https://coro.world.", ["Coro"], ["project", "url"]],
    ],
  ),
  source(
    "traza-product",
    "projects",
    "Traza · Independent project",
    [
      "traza",
      "financial activity",
      "finance",
      "reconciliation",
      "privacy",
      "cloudflare",
      "wallbit",
      "transactions",
      "transfers",
      "investments",
      "tron",
      "usdt",
      "privacidad",
      "finanzas",
    ],
    [
      [
        "traza-purpose",
        "Traza turns fragmented financial data into a traceable story of income, expenses, transfers, and investments.",
        ["Traza"],
        ["project", "product", "motivation"],
      ],
      [
        "traza-motivation",
        "Rodrigo built Traza because transactions alone do not explain a person's financial story; it keeps the account private and traceable while making evidence and uncertainty visible.",
        ["Rodrigo Uroz", "Traza"],
        ["project", "motivation", "privacy"],
      ],
      [
        "traza-domain",
        "Traza uses a provider-independent canonical financial domain model, with transaction intent, entity, and category represented separately.",
        ["Traza"],
        ["project", "architecture", "domain-modeling"],
      ],
      [
        "traza-wallbit-sync",
        "Wallbit is Traza's first read-only provider connector; the system maintains history and supports continuous synchronization.",
        ["Traza", "Wallbit"],
        ["project", "integration", "boundary"],
      ],
      [
        "traza-enrichment",
        "Its enrichment pipeline combines deterministic, public-data, and model-backed enrichment behind a privacy firewall.",
        ["Traza"],
        ["project", "architecture", "ai", "privacy"],
      ],
      [
        "traza-corrections",
        "Private corrections remain private, while only safe public knowledge is eligible for reuse.",
        ["Traza"],
        ["project", "privacy", "data"],
      ],
      [
        "traza-onchain",
        "Traza reconciles on-chain activity, including TRON USDT withdrawals, with provider activity.",
        ["Traza", "TRON", "USDT"],
        ["project", "integration", "reconciliation"],
      ],
      [
        "traza-stack",
        "Traza uses a React, Vite, and TypeScript frontend with a Cloudflare Worker and D1 backend; provider-specific behavior is isolated and provider payloads and credentials stay hidden.",
        ["Traza", "React", "Vite", "TypeScript", "Cloudflare Workers", "D1"],
        ["project", "architecture", "technology", "privacy"],
      ],
      [
        "traza-ownership",
        "Rodrigo is Traza's founder and sole end-to-end builder, covering product, domain modeling, integrations, enrichment and privacy, frontend, backend, deployment, and operations.",
        ["Rodrigo Uroz", "Traza"],
        ["project", "ownership", "role"],
      ],
      [
        "traza-url",
        "Traza is available at https://traza.rodrigouroz.com.",
        ["Traza"],
        ["project", "url"],
      ],
    ],
  ),
  source(
    "ballast-product",
    "projects",
    "Ballast · Independent project",
    [
      "ballast",
      "portfolio",
      "monte carlo",
      "optimization",
      "genetic optimizer",
      "tax lot",
      "fees",
      "taxes",
      "validation lab",
      "broker independent",
      "supuestos",
      "portafolio",
      "optimizacion",
    ],
    [
      [
        "ballast-purpose",
        "Ballast is a public, broker-independent, assumptions-first laboratory for exploring investment plans.",
        ["Ballast"],
        ["project", "product"],
      ],
      [
        "ballast-motivation",
        "Rodrigo built Ballast to make portfolio modeling understandable and auditable, keeping assumptions, allocations, uncertainty, and trade-offs visible instead of hiding them in a black-box recommendation.",
        ["Rodrigo Uroz", "Ballast"],
        ["project", "motivation", "product"],
      ],
      [
        "ballast-experience",
        "Users choose a strategy, investment amount, target, and assumptions, then compare result ranges, drawdowns, and required monthly contributions.",
        ["Ballast"],
        ["project", "product", "simulation"],
      ],
      [
        "ballast-simulation",
        "Ballast runs Monte Carlo simulations locally in the browser.",
        ["Ballast"],
        ["project", "implementation", "simulation", "privacy"],
      ],
      [
        "ballast-optimizer",
        "It uses a genetic optimizer to search for alternative plans and then verifies candidates with exact simulation.",
        ["Ballast"],
        ["project", "implementation", "optimization", "validation"],
      ],
      [
        "ballast-financial-model",
        "Its canonical optimization engine includes tax-lot reconciliation and explicit fee and tax models.",
        ["Ballast"],
        ["project", "domain-modeling", "finance"],
      ],
      [
        "ballast-validation",
        "The implementation normalizes provider data, exposes auditable diagnostics, and includes a Validation Lab with versioned datasets, point-in-time cuts, and leakage-free validation.",
        ["Ballast"],
        ["project", "architecture", "validation", "data"],
      ],
      [
        "ballast-stack",
        "Ballast uses React, Vite, TypeScript, Hono on Cloudflare Workers, and D1.",
        ["Ballast", "React", "Vite", "TypeScript", "Hono", "Cloudflare Workers", "D1"],
        ["project", "implementation", "technology"],
      ],
      [
        "ballast-boundaries",
        "Ballast does not predict markets, execute trades, or present itself as financial advice.",
        ["Ballast"],
        ["project", "boundary"],
      ],
      [
        "ballast-ownership",
        "Rodrigo is Ballast's founder and sole end-to-end builder, covering product definition, financial domain modeling, optimizer and simulator design, frontend, backend, deployment, and validation tooling.",
        ["Rodrigo Uroz", "Ballast"],
        ["project", "ownership", "role"],
      ],
      [
        "ballast-url",
        "Ballast is available at https://ballast-dashboard.pages.dev.",
        ["Ballast"],
        ["project", "url"],
      ],
    ],
  ),
  source(
    "jacara-product",
    "projects",
    "Jacara / Tiny Adventures · Independent project",
    [
      "jacara",
      "tiny adventures",
      "family game",
      "physical-first",
      "computer vision",
      "voice",
      "nara",
      "object hunt",
      "iphone",
      "yaml",
      "camera",
      "microphone",
      "familia",
      "juego",
      "pantallas",
    ],
    [
      [
        "jacara-purpose",
        "Jacara, also known as Tiny Adventures, is a physical-first family game system guided by Nara in the browser.",
        ["Jacara", "Tiny Adventures", "Nara"],
        ["project", "product"],
      ],
      [
        "jacara-motivation",
        "Rodrigo is building Jacara so families spend more time together instead of remaining isolated on separate screens.",
        ["Rodrigo Uroz", "Jacara"],
        ["project", "motivation"],
      ],
      [
        "jacara-phone-role",
        "The phone guides and senses parts of play but is not the game board; the primary play happens among people and their surroundings.",
        ["Jacara"],
        ["project", "product", "design"],
      ],
      [
        "jacara-audience-mechanics",
        "The current indoor experience targets ages five and older with two to six players, using mechanics such as object hunts, rhythm, laughter, voice echo, drawing, and visual memory.",
        ["Jacara"],
        ["project", "audience", "game-design"],
      ],
      [
        "jacara-narrative",
        "Jacara's stories include player decisions and fail-forward outcomes.",
        ["Jacara"],
        ["project", "narrative-design"],
      ],
      [
        "jacara-pipeline",
        "Versioned YAML content is compiled into a canonical abstract syntax tree used by the runtime.",
        ["Jacara", "YAML"],
        ["project", "architecture", "implementation"],
      ],
      [
        "jacara-capabilities",
        "Game mechanics are separated from browser capabilities and enabled only after targeted probes and physical evidence support them.",
        ["Jacara"],
        ["project", "architecture", "validation"],
      ],
      [
        "jacara-audio",
        "Narration audio is pre-generated, validated, and content-addressed; real-time model audio is used only when explicitly required.",
        ["Jacara"],
        ["project", "architecture", "audio", "validation"],
      ],
      [
        "jacara-privacy",
        "Camera and microphone use is bounded, capabilities degrade conservatively, and photos or audio are not retained by default.",
        ["Jacara"],
        ["project", "privacy", "boundary"],
      ],
      [
        "jacara-stack",
        "Jacara uses React, Vite, TypeScript, OpenCV.js, Cloudflare Workers, and OpenAI adapters.",
        ["Jacara", "React", "Vite", "TypeScript", "OpenCV.js", "Cloudflare Workers"],
        ["project", "implementation", "technology"],
      ],
      [
        "jacara-validation",
        "Its acceptance work includes real iPhone and physical family playtests rather than treating a browser build as sufficient evidence.",
        ["Jacara", "iPhone"],
        ["project", "validation"],
      ],
      [
        "jacara-ownership",
        "Rodrigo is Jacara's sole end-to-end builder, covering product and experience design, capability research, content language and compiler, runtime, integrations, narrative, testing, deployment, and operations.",
        ["Rodrigo Uroz", "Jacara"],
        ["project", "ownership", "role"],
      ],
      [
        "jacara-url",
        "Jacara is available at https://jacara.rodrigouroz.com.",
        ["Jacara"],
        ["project", "url"],
      ],
    ],
  ),
  source(
    "utn-education-and-teaching",
    "education",
    "UTN · Education and teaching",
    [
      "utn",
      "systems engineer",
      "education",
      "professor",
      "teaching",
      "systems analysis",
      "operative systems",
      "universidad tecnologica nacional",
      "ingeniero en sistemas",
      "docente",
      "analisis de sistemas",
      "sistemas operativos",
    ],
    [
      [
        "utn-degree",
        "Rodrigo earned a Systems Engineering degree from Universidad Tecnológica Nacional, UTN, graduating in March 2009.",
        ["Rodrigo Uroz", "UTN"],
        ["education", "degree", "date"],
      ],
      [
        "utn-teaching-period",
        "He taught at UTN from 2003 through 2021, a period of eighteen years.",
        ["Rodrigo Uroz", "UTN"],
        ["teaching", "date"],
      ],
      [
        "utn-systems-analysis",
        "For most of that academic career, he taught Systems Analysis as an Adjunct Professor.",
        ["Rodrigo Uroz", "UTN", "Systems Analysis"],
        ["teaching", "role"],
      ],
      [
        "utn-systems-analysis-content",
        "His Systems Analysis course covered the software lifecycle, planning, requirements elicitation, UML, and data modeling.",
        ["Rodrigo Uroz", "UTN", "Systems Analysis"],
        ["teaching", "curriculum"],
      ],
      [
        "utn-operative-systems",
        "He was a Teaching Assistant in the course named Operative Systems during only the first two or three years of his teaching career.",
        ["Rodrigo Uroz", "UTN", "Operative Systems"],
        ["teaching", "role", "date"],
      ],
      [
        "utn-operative-wording",
        "The approved English name of that course is Operative Systems, not Operating Systems.",
        ["UTN", "Operative Systems"],
        ["terminology"],
      ],
    ],
  ),
  source(
    "itba-eoi-coursework",
    "education",
    "ITBA–EOI · Education",
    [
      "itba",
      "eoi",
      "graduate",
      "coursework",
      "thesis",
      "strategic management",
      "posgrado",
      "tesis",
    ],
    [
      [
        "itba-coursework",
        "Rodrigo completed all coursework for a graduate program in Strategic and Technological Management at ITBA–EOI.",
        ["Rodrigo Uroz", "ITBA", "EOI"],
        ["education", "coursework"],
      ],
      [
        "itba-no-degree",
        "He did not submit the thesis, so he did not complete or earn that graduate degree.",
        ["Rodrigo Uroz", "ITBA", "EOI"],
        ["education", "boundary"],
      ],
    ],
  ),
  source(
    "silver-mentoring",
    "capabilities",
    "Silver.dev · Mentoring",
    ["silver", "mentor", "mentoring", "live coding", "system design", "full stack", "mentoria"],
    [
      [
        "silver-role-topics",
        "Rodrigo mentors candidates through Silver.dev in full-stack live coding and system design.",
        ["Rodrigo Uroz", "Silver.dev"],
        ["mentoring", "role", "capability"],
      ],
    ],
  ),
  source(
    "historical-independent-projects",
    "projects",
    "Earlier independent projects",
    [
      "ask holidays",
      "wit ai",
      "housing scraper",
      "telegram",
      "pami",
      "fabric cutting",
      "simulated annealing",
      "rent a coder",
      "vworker",
      "proyectos anteriores",
    ],
    [
      [
        "historical-ask-holidays",
        "Ask Holidays was a Next.js application that used Wit.ai for natural-language holiday queries.",
        ["Ask Holidays", "Next.js", "Wit.ai"],
        ["project", "implementation", "ai"],
      ],
      [
        "historical-housing",
        "Rodrigo built a Python housing scraper that detected new listings and sent Telegram notifications.",
        ["Rodrigo Uroz", "Python", "Telegram"],
        ["project", "implementation", "automation"],
      ],
      [
        "historical-pami",
        "He built a pharmacy PAMI system using Java, JSF, Hibernate, and MySQL.",
        ["Rodrigo Uroz", "PAMI", "Java", "JSF", "Hibernate", "MySQL"],
        ["project", "implementation"],
      ],
      [
        "historical-cutting",
        "He built a fabric-cutting optimizer using simulated annealing and other heuristics in Python with PyGTK.",
        ["Rodrigo Uroz", "Python", "PyGTK"],
        ["project", "implementation", "optimization"],
      ],
      [
        "historical-vworker",
        "He completed roughly three years of Rent a Coder and VWorker projects using PHP, Java, Visual Basic, and C.",
        ["Rodrigo Uroz", "Rent a Coder", "VWorker", "PHP", "Java", "Visual Basic", "C"],
        ["project", "freelance", "technology"],
      ],
    ],
  ),
  source(
    "personal-background",
    "about",
    "Beyond work",
    [
      "hobbies",
      "interests",
      "piano",
      "reading",
      "chess",
      "video games",
      "pasatiempos",
      "intereses",
      "lectura",
      "ajedrez",
      "videojuegos",
    ],
    [
      [
        "personal-interests",
        "Outside work, Rodrigo enjoys playing piano, reading, chess, and video games.",
        ["Rodrigo Uroz"],
        ["personal", "interest"],
      ],
    ],
  ),
];
